from src_v2.preprocess.base.user2item_preprocessor import BaseUser2ItemPreprocessor
from src_v2.preprocess.base.item2item_preprocessor import BaseItem2ItemPreprocessor
from src_v2.preprocess.base.hot_preprocessor import BaseHotPreprocessor
